Update lyric.js
Error:  TypeError: this.__updateHandle__.off is not a function

Here should be to let the player log off the linked lyrics event. Failure to log off will cause the lyrics to move disorderly.
这里应该是让播放器注销联动歌词事件，不注销会导致歌词乱动。